import { addDoc, collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, updateDoc, where, type Unsubscribe } from 'firebase/firestore'
import { db } from '../lib/firebase'
import type { NotificationCategory, NotificationItem, NotificationPriority } from '../types/notification'

const COLLECTION = 'notifications'
function toDate(value: unknown) { if (value && typeof value === 'object' && 'toDate' in value && typeof (value as { toDate?: unknown }).toDate === 'function') return (value as { toDate: () => Date }).toDate(); if (value instanceof Date) return value; return new Date(0) }
function map(id: string, data: Record<string, unknown>): NotificationItem { return { id, workspaceId: String(data.workspaceId ?? ''), recipientId: String(data.recipientId ?? ''), title: String(data.title ?? 'Notification'), message: String(data.message ?? ''), category: String(data.category ?? 'system') as NotificationCategory, priority: String(data.priority ?? 'normal') as NotificationPriority, read: data.read === true, actionPath: data.actionPath ? String(data.actionPath) : undefined, createdBy: data.createdBy ? String(data.createdBy) : undefined, createdAt: toDate(data.createdAt) } }
export function subscribeToNotifications(workspaceId: string, recipientId: string, onChange: (items: NotificationItem[]) => void, onError?: (error: Error) => void): Unsubscribe { if (!workspaceId || !recipientId) return () => undefined; return onSnapshot(query(collection(db, COLLECTION), where('workspaceId', '==', workspaceId), where('recipientId', '==', recipientId)), snap => { const items = snap.docs.map(item => map(item.id, item.data() as Record<string, unknown>)); items.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()); onChange(items) }, error => onError?.(error instanceof Error ? error : new Error('Unable to load notifications.'))) }
export async function createNotification(input: { workspaceId: string; recipientId: string; title: string; message: string; category?: NotificationCategory; priority?: NotificationPriority; actionPath?: string; createdBy?: string }) { if (!input.workspaceId || !input.recipientId || !input.title.trim()) return; await addDoc(collection(db, COLLECTION), { ...input, title: input.title.trim(), message: input.message.trim(), category: input.category ?? 'system', priority: input.priority ?? 'normal', read: false, createdAt: serverTimestamp() }) }
export async function markNotificationRead(id: string) { await updateDoc(doc(db, COLLECTION, id), { read: true, readAt: serverTimestamp() }) }
export async function markAllNotificationsRead(items: NotificationItem[]) { await Promise.all(items.filter(item => !item.read).map(item => markNotificationRead(item.id))) }
export async function deleteNotification(id: string) { await deleteDoc(doc(db, COLLECTION, id)) }
