import { addDoc, collection, deleteDoc, doc, getDocs, query, serverTimestamp, updateDoc, where } from 'firebase/firestore'
import { db } from '../lib/firebase'
import type { CreateWorkshopInput, WorkshopSession } from '../types/workshop'

const COLLECTION = 'calendarEvents'
function asDate(value: unknown): Date { if (value && typeof value === 'object' && 'toDate' in value && typeof (value as { toDate?: unknown }).toDate === 'function') return (value as { toDate: () => Date }).toDate(); if (value instanceof Date) return value; const date = new Date(String(value ?? '')); return Number.isNaN(date.getTime()) ? new Date() : date }
function mapSession(id: string, data: Record<string, unknown>): WorkshopSession { return { id, workspaceId: String(data.workspaceId ?? ''), createdBy: String(data.createdBy ?? ''), institutionName: String(data.institutionName ?? ''), institutionType: (data.institutionType as WorkshopSession['institutionType']) ?? 'college', institutionAddress: String(data.institutionAddress ?? ''), contactPerson: String(data.contactPerson ?? ''), contactNumber: String(data.contactNumber ?? ''), contactEmail: String(data.contactEmail ?? ''), approachDate: String(data.approachDate ?? ''), followUpDate: String(data.followUpDate ?? ''), sessionDate: String(data.sessionDate ?? data.date ?? ''), sessionTime: String(data.sessionTime ?? data.time ?? ''), topic: String(data.topic ?? data.title ?? ''), description: String(data.description ?? ''), mode: (data.mode as WorkshopSession['mode']) ?? 'free', expectedRevenue: Number(data.expectedRevenue ?? 0), finalRevenue: Number(data.finalRevenue ?? 0), participantEstimate: Number(data.participantEstimate ?? 0), speaker: String(data.speaker ?? ''), requirements: String(data.requirements ?? ''), status: (data.status as WorkshopSession['status']) ?? 'lead', notes: String(data.notes ?? data.notes ?? ''), calendarEventId: id, createdAt: asDate(data.createdAt), updatedAt: asDate(data.updatedAt) } }
export async function getWorkshopSessions(workspaceId: string): Promise<WorkshopSession[]> { const snapshot = await getDocs(query(collection(db, COLLECTION), where('workspaceId', '==', workspaceId))); return snapshot.docs.map(item => ({ id: item.id, data: item.data() })).filter(item => String(item.data.entityType ?? '') === 'workshop').map(item => mapSession(item.id, item.data as Record<string, unknown>)).sort((a, b) => (a.sessionDate || '9999').localeCompare(b.sessionDate || '9999')) }
export async function createWorkshopSession(workspaceId: string, createdBy: string, input: CreateWorkshopInput): Promise<WorkshopSession> { const ref = await addDoc(collection(db, COLLECTION), { ...input, entityType: 'workshop', workspaceId, createdBy, title: `Workshop: ${input.topic} — ${input.institutionName}`, date: input.sessionDate, time: input.sessionTime, type: 'meeting', notes: input.notes || input.description, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return { ...input, id: ref.id, workspaceId, createdBy, calendarEventId: ref.id, createdAt: new Date(), updatedAt: new Date() } }
export async function updateWorkshopSession(id: string, workspaceId: string, input: CreateWorkshopInput): Promise<WorkshopSession> { await updateDoc(doc(db, COLLECTION, id), { ...input, entityType: 'workshop', workspaceId, title: `Workshop: ${input.topic} — ${input.institutionName}`, date: input.sessionDate, time: input.sessionTime, type: 'meeting', notes: input.notes || input.description, updatedAt: serverTimestamp() }); return { ...input, id, workspaceId, calendarEventId: id, createdBy: '', createdAt: new Date(), updatedAt: new Date() } }
export async function deleteWorkshopSession(id: string) { await deleteDoc(doc(db, COLLECTION, id)) }