import { Download, X } from 'lucide-react'
import Button from '../ui/Button'
import type { Quotation } from '../../types/quotation'

function money(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0) }
function totalFor(quotation: Quotation) { return Math.max(0, quotation.baseAmount + quotation.thirdPartyCharges + (quotation.domainOpted ? quotation.domainCharges : 0) + quotation.hostingCharges + quotation.extraServices.reduce((sum, item) => sum + item.amount, 0) - quotation.discount) }

export default function QuotationPreviewModal({ quotation, onClose, onPrint }: { quotation: Quotation; onClose: () => void; onPrint: () => void }) {
  const total = totalFor(quotation)
  const extras = quotation.extraServices.filter((item) => item.name.trim())
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-label="Quotation preview">
    <div className="flex h-[95vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-[var(--os-border)] bg-[var(--os-surface)] shadow-2xl">
      <div className="flex shrink-0 items-center justify-between border-b border-[var(--os-border)] px-4 py-3 sm:px-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--os-accent)]">Client preview</p><p className="mt-0.5 text-sm font-semibold text-[var(--os-text)]">{quotation.quotationNumber}</p></div><div className="flex items-center gap-2"><Button variant="secondary" onClick={onPrint}><Download size={14} /> Export PDF</Button><button type="button" onClick={onClose} className="rounded-lg p-2 text-[var(--os-text-muted)] hover:bg-[var(--os-surface-hover)] hover:text-[var(--os-text)]" aria-label="Close preview"><X size={18} /></button></div></div>
      <div className="min-h-0 flex-1 overflow-auto bg-slate-100 p-3 sm:p-8">
        <div className="mx-auto w-full max-w-[794px] bg-white text-slate-900 shadow-lg">
          <div className="border border-slate-200 p-7 sm:p-10">
            <div className="flex items-start justify-between gap-6 border-b-2 border-slate-900 pb-6"><div><div className="inline-flex rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold uppercase tracking-[0.18em] text-white">Quotation</div><h1 className="mt-5 text-2xl font-black tracking-tight sm:text-3xl">{quotation.companyName || 'Your Company'}</h1><p className="mt-1 text-sm text-slate-500">Professional digital solutions & services</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Quotation No.</p><p className="mt-1 text-lg font-bold">{quotation.quotationNumber}</p><p className="mt-3 text-xs text-slate-500">Date: {quotation.date.toLocaleDateString('en-IN')}</p>{quotation.validUntil && <p className="mt-1 text-xs text-slate-500">Valid until: {quotation.validUntil.toLocaleDateString('en-IN')}</p>}</div></div>
            <div className="mt-7 grid gap-6 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Prepared for</p><p className="mt-2 text-lg font-bold">{quotation.clientName || 'Client'}</p>{quotation.businessName && <p className="text-sm text-slate-600">{quotation.businessName}</p>}{quotation.contactNumber && <p className="mt-2 text-xs text-slate-500">{quotation.contactNumber}</p>}{quotation.email && <p className="text-xs text-slate-500">{quotation.email}</p>}{quotation.address && <p className="mt-1 whitespace-pre-wrap text-xs text-slate-500">{quotation.address}</p>}</div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Service delivered by</p><p className="mt-2 text-sm font-bold">{quotation.deliveredBy || quotation.companyName}</p><p className="mt-1 text-xs text-slate-500">{quotation.serviceTitle}</p></div></div>
            <div className="mt-7 overflow-hidden rounded-xl border border-slate-200"><div className="grid grid-cols-[1fr_120px] bg-slate-900 px-4 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-white"><span>Description</span><span className="text-right">Amount</span></div><div className="divide-y divide-slate-100"><Row label={quotation.serviceTitle || 'Main service'} detail={quotation.serviceDescription} amount={quotation.baseAmount} /><Row label="Third-party charges" amount={quotation.thirdPartyCharges} /><Row label={quotation.domainOpted ? 'Domain charges' : 'Domain (not opted)'} amount={quotation.domainOpted ? quotation.domainCharges : 0} /><Row label="Hosting charges" amount={quotation.hostingCharges} />{extras.map((item) => <Row key={item.id} label={item.name} amount={item.amount} />)}</div></div>
            <div className="mt-6 ml-auto w-full max-w-[310px] space-y-2"><Total label="Subtotal" amount={total + quotation.discount} /><Total label="Discount" amount={-quotation.discount} /><div className="mt-3 border-t-2 border-slate-900 pt-3"><Total label="Total" amount={total} strong /></div><Total label="Advance to be paid" amount={quotation.advanceAmount} /><Total label="Balance payable" amount={Math.max(0, total - quotation.advanceAmount)} strong /></div>
            <div className="mt-8 grid gap-5 border-t border-slate-200 pt-5 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Project / Website</p><p className="mt-2 text-sm font-semibold">{quotation.websiteApp || quotation.serviceTitle}</p></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Monthly maintenance</p><p className="mt-2 text-sm font-semibold">{quotation.monthlyMaintenance ? `${money(quotation.monthlyMaintenance)} / month` : 'Not included'}</p></div></div>
            {quotation.externalRemarks && <div className="mt-6 rounded-xl bg-slate-50 p-5"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">Notes & remarks</p><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-slate-600">{quotation.externalRemarks}</p></div>}
            <div className="mt-10 flex items-end justify-between border-t border-slate-200 pt-5"><div><p className="text-xs font-bold">Thank you for your business.</p><p className="mt-1 text-[10px] text-slate-400">This quotation is subject to the agreed scope and payment terms.</p></div><div className="text-right"><p className="text-xs font-semibold">{quotation.companyName}</p><p className="mt-1 text-[10px] text-slate-400">Authorized quotation</p></div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
}
function Row({ label, detail, amount }: { label: string; detail?: string; amount: number }) { return <div className="grid grid-cols-[1fr_120px] px-4 py-3 text-xs"><div><p className="font-semibold">{label}</p>{detail && <p className="mt-1 text-[10px] text-slate-400">{detail}</p>}</div><p className="text-right font-semibold">{money(amount)}</p></div> }
function Total({ label, amount, strong }: { label: string; amount: number; strong?: boolean }) { return <div className="flex justify-between gap-4"><span className={`text-xs ${strong ? 'font-bold' : 'text-slate-500'}`}>{label}</span><span className={`text-xs ${strong ? 'font-bold' : 'font-medium'}`}>{money(amount)}</span></div> }