import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { addDoc, collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, where } from 'firebase/firestore'
import { FileText, Plus, Search, Trash2 } from 'lucide-react'
import Button from '../components/ui/Button'
import Card from '../components/ui/Card'
import ConfirmDialog from '../components/ui/ConfirmDialog'
import SectionHeader from '../components/ui/SectionHeader'
import { useAuth } from '../context/useAuth'
import { useWorkspace } from '../context/useWorkspace'
import { db } from '../lib/firebase'

type BusinessDocument = { id: string; title: string; description: string; category: string; url: string; createdAt?: Date }

export default function Documents() {
  const { user } = useAuth(); const { workspace, loading, hasPermission } = useWorkspace(); const canManage = hasPermission('documents.manage')
  const [items, setItems] = useState<BusinessDocument[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false); const [target, setTarget] = useState<BusinessDocument | null>(null)
  const [form, setForm] = useState({ title: '', description: '', category: 'General', url: '' })
  useEffect(() => { if (loading || !workspace?.id) return undefined; return onSnapshot(query(collection(db, 'documents'), where('workspaceId', '==', workspace.id)), snapshot => setItems(snapshot.docs.map(item => { const d = item.data(); return { id: item.id, title: String(d.title ?? ''), description: String(d.description ?? ''), category: String(d.category ?? 'General'), url: String(d.url ?? ''), createdAt: d.createdAt?.toDate?.() } }).sort((a, b) => (b.createdAt?.getTime() ?? 0) - (a.createdAt?.getTime() ?? 0))), e => { console.error(e); setError('Documents could not be loaded.') }) }, [workspace?.id, loading])
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return items.filter(i => !q || `${i.title} ${i.description} ${i.category}`.toLowerCase().includes(q)) }, [items, search])
  async function createDocument(event: FormEvent) { event.preventDefault(); if (!workspace?.id || !user?.uid || !canManage || !form.title.trim()) return; setSaving(true); setError(''); try { await addDoc(collection(db, 'documents'), { workspaceId: workspace.id, title: form.title.trim(), description: form.description.trim(), category: form.category, url: form.url.trim(), createdBy: user.uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); setForm({ title: '', description: '', category: 'General', url: '' }) } catch (e) { console.error(e); setError('Could not save the document.') } finally { setSaving(false) } }
  async function removeDocument() { if (!target || !canManage) return; setDeleting(true); try { await deleteDoc(doc(db, 'documents', target.id)); setTarget(null) } catch (e) { console.error(e); setError('Could not delete the document.') } finally { setDeleting(false) } }
  return <>
    <div className="mx-auto w-full max-w-[1600px] p-4 sm:p-6 lg:p-8"><SectionHeader title="Documents" description="Keep policies, references, links and important company knowledge organized."/><div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]">{canManage && <Card className="p-6"><SectionHeader title="Add document" description="Store a reference to the source or document."/><form onSubmit={createDocument} className="mt-5 space-y-3"><input required placeholder="Document title" value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} className="w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-4 py-3 text-sm text-[var(--os-text)] outline-none"/><select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))} className="w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-4 py-3 text-sm text-[var(--os-text)]"><option>General</option><option>Policy</option><option>Finance</option><option>Legal</option><option>Operations</option><option>Product</option><option>Reference</option></select><input type="url" placeholder="Source URL (optional)" value={form.url} onChange={e => setForm(f => ({ ...f, url: e.target.value }))} className="w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-4 py-3 text-sm text-[var(--os-text)] outline-none"/><textarea rows={5} placeholder="Description or notes" value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} className="w-full resize-none rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-4 py-3 text-sm text-[var(--os-text)] outline-none"/><Button type="submit" disabled={saving} className="w-full"><Plus size={17}/>{saving ? 'Saving…' : 'Save document'}</Button></form></Card>}
    <Card className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--os-accent)]">Knowledge base</p><h2 className="mt-1 text-xl font-semibold text-[var(--os-text)]">{filtered.length} documents</h2></div><label className="relative block sm:w-72"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--os-text-muted)]"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search documents…" className="w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] py-3 pl-9 pr-3 text-sm text-[var(--os-text)] outline-none"/></label></div>{error && <p className="mt-4 rounded-xl bg-[var(--os-danger-soft)] p-3 text-sm text-[var(--os-danger)]">{error}</p>}<div className="mt-5 grid gap-3 lg:grid-cols-2">{filtered.length ? filtered.map(item => <article key={item.id} className="rounded-2xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--os-accent-soft)] text-[var(--os-accent)]"><FileText size={18}/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold text-[var(--os-text)]">{item.title}</h3>{canManage && <button type="button" onClick={() => setTarget(item)} className="rounded-lg p-2 text-[var(--os-text-muted)] hover:bg-[var(--os-danger-soft)] hover:text-[var(--os-danger)]"><Trash2 size={15}/></button>}</div><p className="mt-1 text-xs text-[var(--os-text-muted)]">{item.category}</p></div></div>{item.description && <p className="mt-4 text-sm leading-6 text-[var(--os-text-secondary)]">{item.description}</p>}{item.url && <a href={item.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-semibold text-[var(--os-accent)]">Open source →</a>}</article>) : <div className="col-span-full rounded-2xl border border-dashed border-[var(--os-border)] p-10 text-center"><FileText className="mx-auto text-[var(--os-text-muted)]" size={30}/><p className="mt-3 text-sm font-medium text-[var(--os-text)]">No documents yet</p></div>}</div></Card></div></div>
    <ConfirmDialog open={Boolean(target)} title="Delete this document?" description={target ? `“${target.title}” will be permanently removed.` : ''} confirmLabel="Delete document" loading={deleting} onCancel={() => !deleting && setTarget(null)} onConfirm={() => void removeDocument()} />
  </>
}
