import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, X } from 'lucide-react'
import Card from '../components/ui/Card'
import ThemeSelect from '../components/ui/ThemeSelect'
import { useAuth } from '../context/useAuth'
import { useWorkspace } from '../context/useWorkspace'
import { subscribeToWorkspaceMembers } from '../services/workspaceService'
import { cancelLeaveRequest, createLeaveRequest, reviewLeaveRequest, subscribeToLeaveRequests } from '../services/leaveService'
import type { LeaveRequest, LeaveStatus, LeaveType } from '../types/leave'
import type { WorkspaceMember } from '../types/workspace'

const types: { value: LeaveType; label: string }[] = [{ value: 'casual', label: 'Casual leave' }, { value: 'sick', label: 'Sick leave' }, { value: 'earned', label: 'Earned leave' }, { value: 'unpaid', label: 'Unpaid leave' }, { value: 'other', label: 'Other' }]
const labels: Record<LeaveStatus, string> = { pending: 'Pending', approved: 'Approved', rejected: 'Rejected', cancelled: 'Cancelled' }

export default function Leave() {
  const { user } = useAuth(); const { workspace, hasPermission } = useWorkspace(); const workspaceId = workspace?.id; const userId = user?.uid
  const canManage = hasPermission('leave.manage'); const canView = hasPermission('leave.view')
  const [items, setItems] = useState<LeaveRequest[]>([]); const [members, setMembers] = useState<WorkspaceMember[]>([]); const [type, setType] = useState<LeaveType>('casual'); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [reason, setReason] = useState(''); const [reviewNote, setReviewNote] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [error, setError] = useState('')

  useEffect(() => { if (!workspaceId || !userId || !canView) return undefined; return subscribeToLeaveRequests(workspaceId, userId, canManage, setItems, e => setError(e.message)) }, [workspaceId, userId, canView, canManage])
  useEffect(() => { if (!workspaceId || !canManage) return undefined; return subscribeToWorkspaceMembers(workspaceId, setMembers, e => setError(e.message)) }, [workspaceId, canManage])
  const stats = useMemo(() => ({ pending: items.filter(i => i.status === 'pending').length, approved: items.filter(i => i.status === 'approved').length }), [items])

  async function submit() { if (!workspaceId || !userId || !startDate || !endDate || !reason.trim() || endDate < startDate) return; setSaving(true); setError(''); try { await createLeaveRequest({ workspaceId, userId, type, startDate, endDate, reason: reason.trim() }); setStartDate(''); setEndDate(''); setReason('') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to submit leave request.') } finally { setSaving(false) } }
  async function review(item: LeaveRequest, status: Extract<LeaveStatus, 'approved' | 'rejected'>) { if (!userId) return; setSaving(true); setError(''); try { await reviewLeaveRequest(item.id, status, userId, reviewNote[item.id] || '') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update leave request.') } finally { setSaving(false) } }

  if (!canView) return <div className="mx-auto w-full max-w-[1400px] p-6"><Card className="p-8 text-center text-sm text-[var(--os-text-secondary)]">You do not have permission to view leave management.</Card></div>
  return <div className="mx-auto w-full max-w-[1400px] p-4 sm:p-6 lg:p-8">
    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--os-accent)]">People & Operations</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[var(--os-text)]">Leave Management</h1><p className="mt-2 text-sm text-[var(--os-text-secondary)]">Request, review and track employee leave in realtime.</p>
    {error && <div role="alert" className="mt-5 rounded-xl bg-[var(--os-danger-soft)] px-4 py-3 text-sm text-[var(--os-danger)]">{error}</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><Card className="p-5"><p className="text-xs text-[var(--os-text-muted)]">Pending</p><p className="mt-1 text-2xl font-semibold text-[var(--os-text)]">{stats.pending}</p></Card><Card className="p-5"><p className="text-xs text-[var(--os-text-muted)]">Approved</p><p className="mt-1 text-2xl font-semibold text-[var(--os-text)]">{stats.approved}</p></Card></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[360px_minmax(0,1fr)]">
      <Card className="p-5"><h2 className="text-sm font-semibold text-[var(--os-text)]">Request leave</h2><div className="mt-4 space-y-3"><ThemeSelect value={type} onChange={v => setType(v as LeaveType)} options={types} placeholder="Leave type"/><input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="os-focus-ring h-11 w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-3 text-sm"/><input type="date" value={endDate} min={startDate || undefined} onChange={e => setEndDate(e.target.value)} className="os-focus-ring h-11 w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-3 text-sm"/><textarea value={reason} onChange={e => setReason(e.target.value)} rows={4} placeholder="Reason for leave" className="os-focus-ring w-full rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-3 py-2.5 text-sm"/><button type="button" disabled={saving || !startDate || !endDate || !reason.trim() || endDate < startDate} onClick={submit} className="h-11 w-full rounded-xl bg-[var(--os-accent)] text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Submit request'}</button></div></Card>
      <Card className="overflow-hidden"><div className="border-b border-[var(--os-border)] px-5 py-4"><h2 className="text-sm font-semibold text-[var(--os-text)]">{canManage ? 'Workspace leave requests' : 'My leave requests'}</h2></div><div className="divide-y divide-[var(--os-border)]">{items.length === 0 ? <div className="p-10 text-center text-sm text-[var(--os-text-secondary)]">No leave requests yet.</div> : items.map(item => { const person = members.find(m => m.userId === item.userId); return <div key={item.id} className="px-5 py-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><CalendarDays size={16} className="text-[var(--os-accent)]"/><p className="text-sm font-semibold text-[var(--os-text)]">{types.find(t => t.value === item.type)?.label}</p><span className="rounded-full bg-[var(--os-accent-soft)] px-2.5 py-1 text-[10px] font-semibold text-[var(--os-accent)]">{labels[item.status]}</span></div><p className="mt-2 text-xs text-[var(--os-text-muted)]">{person?.displayName || (item.userId === userId ? 'You' : item.userId)} · {item.startDate} → {item.endDate}</p><p className="mt-2 text-sm text-[var(--os-text-secondary)]">{item.reason}</p></div>{item.status === 'pending' && item.userId === userId && <button type="button" disabled={saving} onClick={() => cancelLeaveRequest(item.id)} className="inline-flex h-9 items-center justify-center gap-1 rounded-lg border border-[var(--os-border)] px-3 text-xs font-semibold text-[var(--os-text)]"><X size={14}/> Cancel</button>}</div>{canManage && item.status === 'pending' && <div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={reviewNote[item.id] || ''} onChange={e => setReviewNote(prev => ({ ...prev, [item.id]: e.target.value }))} placeholder="Review note (optional)" className="os-focus-ring h-10 min-w-0 flex-1 rounded-lg border border-[var(--os-border)] bg-[var(--os-surface-raised)] px-3 text-xs"/><button type="button" disabled={saving} onClick={() => review(item, 'approved')} className="inline-flex h-10 items-center justify-center gap-1 rounded-lg bg-[var(--os-success)] px-4 text-xs font-semibold text-white"><Check size={14}/> Approve</button><button type="button" disabled={saving} onClick={() => review(item, 'rejected')} className="inline-flex h-10 items-center justify-center gap-1 rounded-lg border border-[var(--os-danger)]/30 px-4 text-xs font-semibold text-[var(--os-danger)]">Reject</button></div>}</div> })}</div></Card>
    </div>
  </div>
}
