import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, CircleDollarSign, Edit3, FolderKanban, Trash2, UserRound } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import Button from '../components/ui/Button'
import Card from '../components/ui/Card'
import ConfirmDialog from '../components/ui/ConfirmDialog'
import ProjectModal from '../components/projects/ProjectModal'
import { useWorkspace } from '../context/useWorkspace'
import { getClients } from '../services/clientService'
import { deleteProject, getProject, updateProject } from '../services/projectService'
import type { Client } from '../types/client'
import type { CreateProjectInput, Project, ProjectPriority, ProjectStatus } from '../types/project'

const statusLabels:Record<ProjectStatus,string>={planning:'Planning','in-development':'In Development','on-hold':'On Hold',testing:'Testing',completed:'Completed',cancelled:'Cancelled'}
const statusClasses:Record<ProjectStatus,string>={planning:'bg-[rgba(139,124,255,0.12)] text-[var(--os-accent)]','in-development':'bg-[rgba(90,169,255,0.12)] text-[var(--os-info)]','on-hold':'bg-[rgba(255,255,255,0.08)] text-[var(--os-text-secondary)]',testing:'bg-[rgba(245,185,66,0.12)] text-[var(--os-warning)]',completed:'bg-[rgba(66,211,146,0.12)] text-[var(--os-success)]',cancelled:'bg-[rgba(255,100,124,0.12)] text-[var(--os-danger)]'}
const priorityLabels:Record<ProjectPriority,string>={low:'Low',medium:'Medium',high:'High',urgent:'Urgent'}
function money(v:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v)}
function dateText(d:Date|null){return d?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(d):'Not set'}
function Item({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-raised)] p-4"><div className="flex items-center gap-2 text-[var(--os-accent)]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--os-text-muted)]">{label}</span></div><p className="mt-2 break-words text-sm font-medium capitalize text-[var(--os-text)]">{value}</p></div>}

function ProjectDetails(){const {projectId}=useParams<{projectId:string}>();const navigate=useNavigate();const {workspace,loading:workspaceLoading}=useWorkspace();const [project,setProject]=useState<Project|null>(null);const [clients,setClients]=useState<Client[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [modalOpen,setModalOpen]=useState(false);const [saving,setSaving]=useState(false);const [deleting,setDeleting]=useState(false);const [confirmOpen,setConfirmOpen]=useState(false);const [modalInstance,setModalInstance]=useState(0)
useEffect(()=>{let cancelled=false;async function load(){if(workspaceLoading)return;if(!workspace?.id||!projectId){setProject(null);setLoading(false);setError('Project could not be found.');return}setLoading(true);setError('');try{const [result,clientResult]=await Promise.all([getProject(projectId,workspace.id),getClients(workspace.id)]);if(!cancelled){setProject(result);setClients(clientResult);if(!result)setError('Project could not be found in this workspace.')}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Failed to load project details.')}finally{if(!cancelled)setLoading(false)}}void load();return()=>{cancelled=true}},[projectId,workspace?.id,workspaceLoading])
function openEdit(){if(!project)return;setError('');setModalInstance(v=>v+1);setModalOpen(true)}
async function save(input:CreateProjectInput){if(!project||!workspace?.id)throw new Error('Workspace is not available.');setSaving(true);setError('');try{const updated=await updateProject(project.id,workspace.id,input);setProject(updated);setModalOpen(false)}catch(e){setError(e instanceof Error?e.message:'Failed to update project.');throw e}finally{setSaving(false)}}
async function confirmDelete(){if(!project||!workspace?.id)return;setDeleting(true);setError('');try{await deleteProject(project.id,workspace.id);navigate('/projects',{replace:true})}catch(e){setError(e instanceof Error?e.message:'Failed to delete project.');setDeleting(false);setConfirmOpen(false)}}
if(loading||workspaceLoading)return <div className="mx-auto w-full max-w-[1400px] p-4 sm:p-6 lg:p-8"><Card className="p-6"><div className="animate-pulse space-y-4"><div className="h-5 w-32 rounded bg-[var(--os-surface-hover)]"/><div className="h-10 w-2/3 rounded bg-[var(--os-surface-hover)]"/><div className="grid gap-4 md:grid-cols-3"><div className="h-24 rounded-xl bg-[var(--os-surface-hover)]"/><div className="h-24 rounded-xl bg-[var(--os-surface-hover)]"/><div className="h-24 rounded-xl bg-[var(--os-surface-hover)]"/></div></div></Card></div>
if(!project)return <div className="mx-auto w-full max-w-[1400px] p-4 sm:p-6 lg:p-8"><Card className="p-8 text-center"><FolderKanban size={30} className="mx-auto text-[var(--os-accent)]"/><h1 className="mt-4 text-xl font-semibold text-[var(--os-text)]">Project not found</h1><p className="mt-2 text-sm text-[var(--os-text-secondary)]">{error||'This project is no longer available.'}</p><Button type="button" className="mt-6" onClick={()=>navigate('/projects')}><ArrowLeft size={16}/> Back to Projects</Button></Card></div>
return <div className="mx-auto w-full max-w-[1400px] p-4 sm:p-6 lg:p-8"><button type="button" onClick={()=>navigate('/projects')} className="os-focus-ring mb-6 inline-flex items-center gap-2 rounded-lg text-sm font-medium text-[var(--os-text-secondary)] hover:text-[var(--os-text)]"><ArrowLeft size={16}/>Back to Projects</button>{error&&<div role="alert" className="mb-6 rounded-xl border border-[rgba(255,100,124,0.25)] bg-[rgba(255,100,124,0.08)] px-4 py-3 text-sm text-[var(--os-danger)]">{error}</div>}
<section className="mb-6 flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[var(--os-accent-soft)] text-[var(--os-accent)]"><FolderKanban size={25}/></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold tracking-tight text-[var(--os-text)] sm:text-4xl">{project.name}</h1><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClasses[project.status]}`}>{statusLabels[project.status]}</span></div><p className="mt-2 text-sm text-[var(--os-text-secondary)]">{project.clientName||'No client assigned'}</p></div></div><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={openEdit} disabled={deleting}><Edit3 size={15}/> Edit Project</Button><Button type="button" variant="secondary" onClick={()=>setConfirmOpen(true)} disabled={deleting||saving}><Trash2 size={15}/>{deleting?'Deleting...':'Delete'}</Button></div></section>
<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Item icon={<UserRound size={16}/>} label="Client" value={project.clientName||'Not assigned'}/><Item icon={<FolderKanban size={16}/>} label="Type" value={project.type.replace('-', ' ')}/><Item icon={<CircleDollarSign size={16}/>} label="Project Value" value={money(project.projectValue)}/><Item icon={<CircleDollarSign size={16}/>} label="Budget" value={money(project.budget)}/></div>
<div className="mt-4 grid gap-4 lg:grid-cols-3"><Card className="p-5 lg:col-span-2"><h2 className="text-sm font-semibold text-[var(--os-text)]">Project Snapshot</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Item icon={<CalendarDays size={16}/>} label="Start Date" value={dateText(project.startDate)}/><Item icon={<CalendarDays size={16}/>} label="Deadline" value={dateText(project.deadline)}/><Item icon={<FolderKanban size={16}/>} label="Priority" value={priorityLabels[project.priority]}/><Item icon={<CircleDollarSign size={16}/>} label="Value vs Budget" value={money(project.projectValue-project.budget)}/></div></Card><Card className="p-5"><h2 className="text-sm font-semibold text-[var(--os-text)]">Timeline</h2><div className="mt-5 space-y-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--os-text-muted)]">Created</p><p className="mt-1 text-sm text-[var(--os-text-secondary)]">{dateText(project.createdAt)}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--os-text-muted)]">Last Updated</p><p className="mt-1 text-sm text-[var(--os-text-secondary)]">{dateText(project.updatedAt)}</p></div></div></Card></div>
<Card className="mt-4 p-5"><h2 className="text-sm font-semibold text-[var(--os-text)]">Description</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[var(--os-text-secondary)]">{project.description||'No project description added.'}</p></Card><Card className="mt-4 p-5"><h2 className="text-sm font-semibold text-[var(--os-text)]">Notes</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[var(--os-text-secondary)]">{project.notes||'No notes added.'}</p></Card>
<ProjectModal key={`project-details-modal-${modalInstance}`} open={modalOpen} project={project} clients={clients} saving={saving} onClose={()=>!saving&&setModalOpen(false)} onSubmit={save}/><ConfirmDialog open={confirmOpen} title="Delete project?" description={<>You are about to permanently delete <strong>{project.name}</strong>. This cannot be undone.</>} confirmLabel="Delete Project" loading={deleting} onCancel={()=>!deleting&&setConfirmOpen(false)} onConfirm={confirmDelete}/></div>}
export default ProjectDetails
