import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Activity, CalendarDays, Clock3, Gauge, UserCheck } from 'lucide-react'
import Card from '../ui/Card'
import { useAuth } from '../../context/useAuth'
import { useWorkspace } from '../../context/useWorkspace'
import { subscribeToAttendance } from '../../services/attendanceService'
import { subscribeToLeaveRequests } from '../../services/leaveService'
import type { AttendanceRecord } from '../../types/attendance'
import type { LeaveRequest } from '../../types/leave'

const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const minutesBetween = (a?: Date, b?: Date) => a && b ? Math.max(0, Math.round((b.getTime() - a.getTime()) / 60000)) : 0

export default function AttendanceAnalyticsPanel() {
  const { user } = useAuth(); const { workspace, hasPermission } = useWorkspace(); const canView = hasPermission('attendance.view'); const canManage = hasPermission('attendance.manage')
  const [attendance, setAttendance] = useState<AttendanceRecord[]>([]); const [leaves, setLeaves] = useState<LeaveRequest[]>([])
  useEffect(() => { if (!workspace?.id || !user?.uid || !canView) return undefined; const now = new Date(); const start = dateKey(new Date(now.getFullYear(), now.getMonth(), 1)); const end = dateKey(new Date(now.getFullYear(), now.getMonth() + 1, 0)); return subscribeToAttendance(workspace.id, start, end, canManage, user.uid, setAttendance, () => undefined) }, [workspace?.id, user?.uid, canView, canManage])
  useEffect(() => { if (!workspace?.id || !user?.uid) return undefined; return subscribeToLeaveRequests(workspace.id, user.uid, canManage, setLeaves, () => undefined) }, [workspace?.id, user?.uid, canManage])
  const stats = useMemo(() => { const now = new Date(); const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const working = attendance.filter(item => ['present', 'late', 'half-day'].includes(item.status)); const present = attendance.filter(item => item.status === 'present').length; const late = attendance.filter(item => item.status === 'late').length; const absent = attendance.filter(item => item.status === 'absent').length; const leave = attendance.filter(item => item.status === 'leave').length; const checkedOut = attendance.filter(item => item.checkOut).length; const minutes = attendance.reduce((sum, item) => sum + minutesBetween(item.checkIn, item.checkOut), 0); const checkInCount = attendance.filter(item => item.checkIn).length; const avg = checkedOut ? Math.round(minutes / checkedOut) : 0; const expected = Math.max(1, days - 8); const utilization = Math.min(100, Math.round(working.length / expected * 100)); const punctuality = working.length ? Math.round(present / working.length * 100) : 0; const leaveDays = leaves.reduce((sum, item) => { const a = new Date(`${item.startDate}T12:00:00`); const b = new Date(`${item.endDate}T12:00:00`); return sum + (Number.isNaN(a.getTime()) || Number.isNaN(b.getTime()) ? 0 : Math.max(1, Math.floor((b.getTime() - a.getTime()) / 86400000) + 1)) }, 0); return { working: working.length, present, late, absent, leave, checkedOut, minutes, avg, checkInRate: attendance.length ? Math.round(checkInCount / attendance.length * 100) : 0, utilization, punctuality, leaveDays, leaveRequests: leaves.length } }, [attendance, leaves])
  const recentDays = useMemo(() => Array.from({ length: 7 }, (_, index) => { const d = new Date(); d.setDate(d.getDate() - (6 - index)); const key = dateKey(d); const record = attendance.find(item => item.date === key && (!canManage || item.userId === user?.uid)); return { key, label: d.toLocaleDateString('en-IN', { weekday: 'short' }), status: record?.status ?? 'none' } }), [attendance, canManage, user?.uid])
  if (!canView) return null
  return <Card className="p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--os-accent-soft)] text-[var(--os-accent)]"><Activity size={17} /></span><div><h2 className="text-sm font-semibold text-[var(--os-text)]">Attendance intelligence</h2><p className="text-xs text-[var(--os-text-muted)]">Live workforce health for {new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</p></div></div><span className="rounded-full bg-[var(--os-success-soft)] px-2.5 py-1 text-[10px] font-semibold text-[var(--os-success)]">Realtime</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi icon={<UserCheck size={15} />} label="Present" value={String(stats.present)} detail={`${stats.punctuality}% punctuality`} /><Kpi icon={<Clock3 size={15} />} label="Avg work time" value={`${Math.floor(stats.avg / 60)}h ${stats.avg % 60}m`} detail={`${stats.checkedOut} completed check-outs`} /><Kpi icon={<Gauge size={15} />} label="Check-in rate" value={`${stats.checkInRate}%`} detail={`${stats.working} working records`} /><Kpi icon={<CalendarDays size={15} />} label="Leave usage" value={`${stats.leaveDays} days`} detail={`${stats.leaveRequests} requests`} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--os-text-muted)]">Last 7 days</p><div className="mt-3 grid grid-cols-7 gap-2">{recentDays.map(day => <div key={day.key} className="rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-hover)] p-2 text-center"><p className="text-[9px] font-semibold text-[var(--os-text-muted)]">{day.label}</p><div className={`mx-auto mt-2 h-3 w-3 rounded-full ${day.status === 'present' ? 'bg-[var(--os-success)]' : day.status === 'late' ? 'bg-[var(--os-warning)]' : day.status === 'absent' ? 'bg-[var(--os-danger)]' : day.status === 'leave' ? 'bg-[var(--os-accent)]' : 'bg-[var(--os-border-strong)]'}`} /><p className="mt-2 truncate text-[9px] capitalize text-[var(--os-text-muted)]">{day.status.replace('-', ' ')}</p></div>)}</div></div><div className="grid grid-cols-2 gap-3"><Small label="Late" value={String(stats.late)} /><Small label="Absent" value={String(stats.absent)} /><Small label="Leave marked" value={String(stats.leave)} /><Small label="Work time" value={`${Math.floor(stats.minutes / 60)}h ${stats.minutes % 60}m`} /><Small label="Attendance utilization" value={`${stats.utilization}%`} /><Small label="Check-outs" value={String(stats.checkedOut)} /></div></div></Card>
}
function Kpi({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <div className="rounded-xl border border-[var(--os-border)] bg-[var(--os-surface-hover)] p-3"><div className="flex items-center gap-2 text-[var(--os-accent)]">{icon}<span className="text-[10px] font-semibold uppercase tracking-wide text-[var(--os-text-muted)]">{label}</span></div><p className="mt-2 text-lg font-bold text-[var(--os-text)]">{value}</p><p className="mt-1 text-[10px] text-[var(--os-text-muted)]">{detail}</p></div> }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[var(--os-border)] p-3"><p className="text-[10px] uppercase tracking-wide text-[var(--os-text-muted)]">{label}</p><p className="mt-1 text-sm font-bold text-[var(--os-text)]">{value}</p></div> }