import { useEffect, useRef, useState } from 'react'
import { Bell, CheckCheck, ExternalLink } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/useAuth'
import { useWorkspace } from '../../context/useWorkspace'
import { markAllNotificationsRead, markNotificationRead, subscribeToNotifications } from '../../services/notificationService'
import type { NotificationItem } from '../../types/notification'

export default function NotificationBell() {
  const { user } = useAuth(); const { workspace, loading } = useWorkspace(); const navigate = useNavigate(); const [items, setItems] = useState<NotificationItem[]>([]); const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null)
  useEffect(() => { if (loading || !workspace?.id || !user?.uid) return undefined; return subscribeToNotifications(workspace.id, user.uid, setItems) }, [workspace?.id, loading, user?.uid])
  useEffect(() => { if (!open) return undefined; const close = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open])
  const unread = items.filter(item => !item.read); const recent = items.slice(0, 6)
  async function openItem(item: NotificationItem) { if (!item.read) await markNotificationRead(item.id); setOpen(false); if (item.actionPath) navigate(item.actionPath) }
  return <div ref={ref} className="relative"><button type="button" aria-label={`Notifications${unread.length ? `, ${unread.length} unread` : ''}`} aria-expanded={open} onClick={() => setOpen(value => !value)} className="os-focus-ring relative flex h-10 w-10 items-center justify-center rounded-xl text-[var(--os-text-secondary)] transition-colors hover:bg-[var(--os-surface-hover)] hover:text-[var(--os-text)]"><Bell size={19} />{unread.length > 0 && <span className="absolute right-1.5 top-1.5 flex min-h-4 min-w-4 items-center justify-center rounded-full bg-[var(--os-danger)] px-1 text-[8px] font-bold text-white">{unread.length > 9 ? '9+' : unread.length}</span>}</button>{open && <div className="absolute right-0 top-12 z-[80] w-[360px] max-w-[calc(100vw-2rem)] overflow-hidden rounded-2xl border border-[var(--os-border-strong)] bg-[var(--os-surface-raised)] shadow-[var(--os-shadow-lg)]"><div className="flex items-center justify-between border-b border-[var(--os-border)] px-4 py-3"><div><p className="text-sm font-semibold text-[var(--os-text)]">Notifications</p><p className="text-[10px] text-[var(--os-text-muted)]">{unread.length ? `${unread.length} unread` : 'All caught up'}</p></div>{unread.length > 0 && <button type="button" onClick={() => void markAllNotificationsRead(items)} className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--os-accent)]"><CheckCheck size={13} /> Read all</button>}</div><div className="max-h-[390px] overflow-y-auto">{recent.length ? recent.map(item => <button type="button" key={item.id} onClick={() => void openItem(item)} className={`flex w-full gap-3 border-b border-[var(--os-border)] p-4 text-left hover:bg-[var(--os-surface-hover)] ${item.read ? '' : 'bg-[var(--os-accent-soft)]/30'}`}><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[var(--os-accent)]" style={{ opacity: item.read ? 0 : 1 }} /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-[var(--os-text)]">{item.title}</span><span className="mt-1 block line-clamp-2 text-[11px] leading-4 text-[var(--os-text-muted)]">{item.message}</span><span className="mt-1 block text-[9px] text-[var(--os-text-muted)]">{item.createdAt.getTime() ? item.createdAt.toLocaleString('en-IN') : 'Just now'}</span></span>{item.actionPath && <ExternalLink size={13} className="mt-1 shrink-0 text-[var(--os-text-muted)]" />}</button>) : <div className="p-10 text-center text-xs text-[var(--os-text-muted)]">No notifications yet.</div>}</div><button type="button" onClick={() => { setOpen(false); navigate('/notifications') }} className="w-full border-t border-[var(--os-border)] px-4 py-3 text-xs font-semibold text-[var(--os-accent)] hover:bg-[var(--os-surface-hover)]">View all notifications</button></div>}</div>
}
